### ISSUE TITLE
crash on server 

### ISSUE THREAD

**Issue by MehanikTMYT** [Nitespring/AlchemistArsenal#1]
-- Mod loading issue for: alkhars --
Details:
	Mod file: /content/gdrive/MyDrive/server/mods/AlchemistsArsenal-Neoforge1.21-v1.1.0.1.jar
	Failure message: Alchemist's Arsenal (alkhars) encountered an error while dispatching the net.neoforged.neoforge.registries.RegisterEvent event
		java.lang.NullPointerException: Trying to access unbound value: ResourceKey[minecraft:item / alkhars:automatic_crossbow]
	Mod version: 1.1.0.1
	Mod issues URL: <No issues URL found>
	Exception message: java.lang.NullPointerException: Trying to access unbound value: ResourceKey[minecraft:item / alkhars:automatic_crossbow]
Stacktrace:
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredHolder.value(DeferredHolder.java:103) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredHolder.get(DeferredHolder.java:117) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/alkhars@1.1.0.1/github.nitespring.alchemistarsenal.core.init.CreativeTabInit.lambda$static$1(CreativeTabInit.java:20) ~[AlchemistsArsenal-Neoforge1.21-v1.1.0.1.jar%23304!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:215) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$register$1(DeferredRegister.java:234) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$addEntries$2(DeferredRegister.java:375) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.RegisterEvent.register(RegisterEvent.java:48) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.addEntries(DeferredRegister.java:375) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:329) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:177) ~[loader-4.0.34.jar%2360!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.lambda$postEventWithWrapInModOrder$16(ModLoader.java:379) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:174) ~[loader-4.0.34.jar%2360!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:377) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:368) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.GameData.postRegisterEvents(GameData.java:92) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.internal.CommonModLoader.lambda$begin$0(CommonModLoader.java:54) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}

**Comment by MehanikTMYT** [comment]
i have else error with up: -- Head --
Thread: main
Stacktrace:
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:220) ~[securejarhandler-3.0.8.jar:?] {}
-- Mod loading issue for: alkhars --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/model/Model
		at TRANSFORMER/alkhars@1.1.0.1/github.nitespring.alchemistarsenal.common.item.equipment.SteampunkSuitItem.<clinit>(SteampunkSuitItem.java:134) ~[AlchemistsArsenal-Neoforge1.21-v1.1.0.1.jar%23304!/:?] {re:classloading}
		at TRANSFORMER/alkhars@1.1.0.1/github.nitespring.alchemistarsenal.core.init.ItemInit.lambda$static$1(ItemInit.java:31) ~[AlchemistsArsenal-Neoforge1.21-v1.1.0.1.jar%23304!/:?] {re:classloading}
		at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:215) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
		at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$register$1(DeferredRegister.java:234) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
		at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$addEntries$2(DeferredRegister.java:375) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
		at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.RegisterEvent.register(RegisterEvent.java:48) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
		at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.addEntries(DeferredRegister.java:375) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
		at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.2.jar%2367!/:?] {}
		at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2367!/:?] {}
		at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:329) ~[bus-8.0.2.jar%2367!/:?] {}
		at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:177) ~[loader-4.0.34.jar%2360!/:4.0] {re:mixin}
		at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.lambda$postEventWithWrapInModOrder$16(ModLoader.java:379) ~[loader-4.0.34.jar%2360!/:4.0] {}
		at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
		at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:174) ~[loader-4.0.34.jar%2360!/:4.0] {re:mixin}
		at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:377) ~[loader-4.0.34.jar%2360!/:4.0] {}
		at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:368) ~[loader-4.0.34.jar%2360!/:4.0] {}
		at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.GameData.postRegisterEvents(GameData.java:92) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
		at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.internal.CommonModLoader.lambda$begin$0(CommonModLoader.java:54) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
		at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}

	Mod file: /content/gdrive/MyDrive/server/mods/AlchemistsArsenal-Neoforge1.21-v1.1.0.1.jar
	Failure message: Alchemist's Arsenal (alkhars) encountered an error while dispatching the net.neoforged.neoforge.registries.RegisterEvent event
		java.lang.NoClassDefFoundError: net/minecraft/client/model/Model
	Mod version: 1.1.0.1
	Mod issues URL: <No issues URL found>
	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.model.Model
Stacktrace:
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:220) ~[securejarhandler-3.0.8.jar:?] {}
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
	at TRANSFORMER/alkhars@1.1.0.1/github.nitespring.alchemistarsenal.common.item.equipment.SteampunkSuitItem.<clinit>(SteampunkSuitItem.java:134) ~[AlchemistsArsenal-Neoforge1.21-v1.1.0.1.jar%23304!/:?] {re:classloading}
	at TRANSFORMER/alkhars@1.1.0.1/github.nitespring.alchemistarsenal.core.init.ItemInit.lambda$static$1(ItemInit.java:31) ~[AlchemistsArsenal-Neoforge1.21-v1.1.0.1.jar%23304!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:215) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$register$1(DeferredRegister.java:234) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.lambda$addEntries$2(DeferredRegister.java:375) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.RegisterEvent.register(RegisterEvent.java:48) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.DeferredRegister.addEntries(DeferredRegister.java:375) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:329) ~[bus-8.0.2.jar%2367!/:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:177) ~[loader-4.0.34.jar%2360!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.lambda$postEventWithWrapInModOrder$16(ModLoader.java:379) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModList.forEachModInOrder(ModList.java:174) ~[loader-4.0.34.jar%2360!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:377) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:368) ~[loader-4.0.34.jar%2360!/:4.0] {}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.registries.GameData.postRegisterEvents(GameData.java:92) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at TRANSFORMER/neoforge@21.1.92/net.neoforged.neoforge.internal.CommonModLoader.lambda$begin$0(CommonModLoader.java:54) ~[neoforge-21.1.92-universal.jar%23293!/:?] {re:classloading}
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}

**Comment by Nitespring** [comment]
Try using an older Neoforge version until I update the mod

**Comment by MehanikTMYT** [comment]
It’s already latest

**Comment by MehanikTMYT** [comment]
But thanks for your reply

**Comment by Nitespring** [comment]
> It’s already latest

an older version, not a newer one
